version: '3'

services:
  consul:
    image: consul
    ports:
      - '8500:8500'

  user-service:
    build: .
    environment:
      - CONSUL_ADDRESS=consul:8500
    ports:
      - '8081:8080'

  order-service:
    build: .
    environment:
      - CONSUL_ADDRESS=consul:8500
    ports:
      - '8082:8080'

  gateway:
    build: .
    environment:
      - CONSUL_ADDRESS=consul:8500
    ports:
      - '8080:8080'
